// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgqtjjkyfyumqcoorjmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncXRqamt5Znl1bXFjb29yam1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjgxNTksImV4cCI6MjA2NTIwNDE1OX0.F-hsh9hjIPoBfWnmQ-7nLARFg3M9Y7k3MSm-dnQHP00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);